{ pythonPackages, buildPythonPackage, tahoe-lafs-version, tahoe-lafs-src }:
buildPythonPackage rec {
  pname = "tahoe-lafs";
  version = tahoe-lafs-version;
  src = tahoe-lafs.src;
  # The source doesn't include version information - so dump some in
  # to it here.
  postPatch =
    let
      versionContent = builtins.toFile "_version.py" ''
        # This _version.py is generated by tahoe-lafs.nix.

        __pkgname__ = "tahoe-lafs"

        # TODO: We can have more metadata after we switch to flakes.
        # Then the `self` input will have a `sourceInfo` attribute telling us
        # things like git revision, a revision counter, etc.
        real_version = "${version}"
        full_version = real_version
        branch = "master"
        verstr = real_version
        __version__ = verstr
      '';
    in
      ''
        cp ${versionContent} src/allmydata/_version.py
      '';

  dontUseSetuptoolsCheck = true;
  propagatedBuildInputs = with pythonPackages; [
    zfec
    zope_interface
    foolscap
    cryptography
    twisted
    pyyaml
    six
    magic-wormhole
    eliot
    pyrsistent
    attrs
    autobahn
    future
    netifaces
    pyutil
    collections-extended
    klein
    werkzeug
    treq
    cbor2
    pycddl
    click
    psutil
    filelock
    distro
    appdirs
    bcrypt
    aniso8601
  ];
}
