#!/usr/bin/env bash

export PYTHONPATH=.
pip-compile -q --allow-unsafe requirements/base.in -o requirements/base.txt
pip-compile -q --allow-unsafe requirements/test.in -o requirements/test.txt --pip-args "-c requirements/base.txt"
