#!/usr/bin/env bash

export PYTHONPATH=.
pip-compile -q requirements/base.in -o requirements/base.txt
pip-compile -q requirements/test.in -o requirements/test.txt --pip-args "-c requirements/base.txt"

sed -i '\,https://github.com/tahoe-lafs/tahoe-lafs,s,.*,tahoe-lafs,' requirements/base.txt
